# Generated by Django 4.2.9 on 2026-01-04 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        help_text="User role at conversation start",
                        max_length=20,
                        verbose_name="User Role",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Conversation title (auto-generated or custom)",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of conversation",
                        verbose_name="Summary",
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="Total tokens used in this conversation",
                        verbose_name="Total Tokens",
                    ),
                ),
                (
                    "total_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated total cost in USD",
                        max_digits=10,
                        verbose_name="Total Cost (USD)",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Is this conversation archived?",
                        verbose_name="Archived",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        help_text="Message sender role",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message content", verbose_name="Content"
                    ),
                ),
                (
                    "tokens_input",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of input tokens",
                        null=True,
                        verbose_name="Input Tokens",
                    ),
                ),
                (
                    "tokens_output",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of output tokens",
                        null=True,
                        verbose_name="Output Tokens",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        help_text="LLM model that generated this message",
                        max_length=50,
                        verbose_name="Model Used",
                    ),
                ),
                (
                    "retrieved_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Documents retrieved from RAG for this message",
                        verbose_name="Retrieved Documents",
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Response latency in milliseconds",
                        null=True,
                        verbose_name="Latency (ms)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.conversation",
                        verbose_name="Conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
    ]
