# Generated by Django 4.2.9 on 2026-01-04 08:49

import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "property_name",
                    models.CharField(
                        help_text="Name or title of the property",
                        max_length=200,
                        verbose_name="Property Name",
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in US dollars",
                        max_digits=12,
                        verbose_name="Price (USD)",
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of bedrooms",
                        null=True,
                        verbose_name="Bedrooms",
                    ),
                ),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Number of bathrooms (can be 2.5, etc.)",
                        max_digits=3,
                        null=True,
                        verbose_name="Bathrooms",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("condo", "Condominium"),
                            ("villa", "Villa"),
                            ("land", "Land"),
                            ("commercial", "Commercial"),
                            ("apartment", "Apartment"),
                        ],
                        help_text="Type of property",
                        max_length=20,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("off_market", "Off Market"),
                        ],
                        default="available",
                        help_text="Current status of the property",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="City, region, or area",
                        max_length=200,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS latitude coordinate",
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS longitude coordinate",
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full property description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "square_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Property size in square meters",
                        max_digits=10,
                        null=True,
                        verbose_name="Square Meters",
                    ),
                ),
                (
                    "lot_size_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lot size in square meters",
                        max_digits=10,
                        null=True,
                        verbose_name="Lot Size (m²)",
                    ),
                ),
                (
                    "hoa_fee_monthly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly HOA/maintenance fee in USD",
                        max_digits=10,
                        null=True,
                        verbose_name="HOA Fee (Monthly)",
                    ),
                ),
                (
                    "property_tax_annual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual property tax in USD",
                        max_digits=10,
                        null=True,
                        verbose_name="Property Tax (Annual)",
                    ),
                ),
                (
                    "amenities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="List of amenities (pool, gym, etc.)",
                        size=None,
                        verbose_name="Amenities",
                    ),
                ),
                (
                    "year_built",
                    models.IntegerField(
                        blank=True,
                        help_text="Year property was constructed",
                        null=True,
                        verbose_name="Year Built",
                    ),
                ),
                (
                    "parking_spaces",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of parking spaces",
                        null=True,
                        verbose_name="Parking Spaces",
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text="Which user roles can see this property",
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Original listing URL",
                        max_length=500,
                        null=True,
                        verbose_name="Source URL",
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(
                        blank=True,
                        help_text="Original HTML content for backup",
                        null=True,
                        verbose_name="Raw HTML",
                    ),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score from LLM extraction (0-1)",
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Confidence score per field",
                        verbose_name="Field Confidence",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When data was extracted",
                        null=True,
                        verbose_name="Extracted At",
                    ),
                ),
                (
                    "last_verified",
                    models.DateTimeField(
                        blank=True,
                        help_text="When data was last manually verified",
                        null=True,
                        verbose_name="Last Verified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this property listing active?",
                        verbose_name="Active",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Vector embedding for semantic search",
                        null=True,
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Optimized text for semantic search",
                        verbose_name="Search Content",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, help_text="Full-text search vector", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "db_table": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(help_text="Image URL", max_length=500)),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="Image caption", max_length=200
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the primary image?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_images",
                "ordering": ["order", "-is_primary", "created_at"],
            },
        ),
    ]
