# Generated by Django 4.2.9 on 2026-01-04 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_properties",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verified By",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyimage",
            index=models.Index(
                fields=["property", "order"], name="property_im_propert_3dfd5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["tenant", "status", "is_active"],
                name="properties_tenant__386e63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type", "location"],
                name="properties_propert_ac4471_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["price_usd"], name="properties_price_u_8c42da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["-created_at"], name="properties_created_2ede73_idx"
            ),
        ),
    ]
