# Generated by Django 4.2.9 on 2026-01-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_property_unique_property_per_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Full property description",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="City, region, or area",
                max_length=200,
                null=True,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price in US dollars",
                max_digits=12,
                null=True,
                verbose_name="Price (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_name",
            field=models.CharField(
                blank=True,
                help_text="Name or title of the property",
                max_length=200,
                null=True,
                verbose_name="Property Name",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("house", "House"),
                    ("condo", "Condominium"),
                    ("villa", "Villa"),
                    ("land", "Land"),
                    ("commercial", "Commercial"),
                    ("apartment", "Apartment"),
                ],
                help_text="Type of property",
                max_length=20,
                null=True,
                verbose_name="Property Type",
            ),
        ),
    ]
