# Generated by Django 4.2.9 on 2026-01-04 08:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_enable_pgvector"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Document text content", verbose_name="Content"
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Vector embedding for semantic search",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about this document",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        help_text="Which user roles can access this document",
                        size=None,
                        verbose_name="Accessible to Roles",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("property", "Property Information"),
                            ("investment", "Investment Information"),
                            ("legal", "Legal Information"),
                            ("market", "Market Analysis"),
                            ("amenity", "Amenity Information"),
                            ("activity", "Activity Information"),
                            ("restaurant", "Restaurant Information"),
                            ("tour", "Tour Information"),
                            ("demand", "Demand Information"),
                            ("pricing", "Pricing Information"),
                            ("service", "Service Information"),
                            ("sop", "Standard Operating Procedure"),
                            ("vendor", "Vendor Information"),
                            ("maintenance", "Maintenance Information"),
                            ("guest", "Guest Information"),
                        ],
                        help_text="Type of content in this document",
                        max_length=50,
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "freshness_date",
                    models.DateField(
                        help_text="Date when this information was current",
                        verbose_name="Freshness Date",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Source URL if applicable",
                        max_length=500,
                        null=True,
                        verbose_name="Source URL",
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable source reference",
                        max_length=200,
                        verbose_name="Source Reference",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this document active for retrieval?",
                        verbose_name="Active",
                    ),
                ),
                (
                    "times_retrieved",
                    models.IntegerField(
                        default=0,
                        help_text="How many times this document was retrieved in RAG",
                        verbose_name="Times Retrieved",
                    ),
                ),
                (
                    "avg_relevance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Average relevance score when retrieved",
                        max_digits=4,
                        null=True,
                        verbose_name="Average Relevance Score",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="documents_tenant__d3c9b3_idx",
                    ),
                    models.Index(
                        fields=["content_type", "is_active"],
                        name="documents_content_e9e832_idx",
                    ),
                    models.Index(
                        fields=["freshness_date"], name="documents_freshne_6e6af8_idx"
                    ),
                    models.Index(
                        fields=["-times_retrieved"], name="documents_times_r_ff2d18_idx"
                    ),
                ],
            },
        ),
    ]
