# Generated by Django 4.2.9 on 2026-01-04 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the organization or client",
                        max_length=200,
                        verbose_name="Tenant Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "domain",
                    models.URLField(
                        help_text="Primary domain for this tenant",
                        unique=True,
                        verbose_name="Domain",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom configuration for this tenant",
                        verbose_name="Settings",
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("pro", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basic",
                        max_length=50,
                        verbose_name="Subscription Tier",
                    ),
                ),
                (
                    "max_properties",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum number of properties allowed",
                        verbose_name="Max Properties",
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum number of users allowed",
                        verbose_name="Max Users",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this tenant currently active?",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="tenants_is_acti_c0e134_idx",
                    ),
                ],
            },
        ),
    ]
